fleetdashboard/main/__init__.py
# This bluepint will deal with main app functionality

from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')

from . import views, main_forms

fleetdashboard/main/views.py
from fleetdashboard import db
from . import main
from fleetdashboard.models import Vehicle, Status, Expense, Notification, NotifList, History

from flask import (
    render_template,
    redirect,
    flash,
    url_for,
    session,
    request,
    jsonify,
    current_app
)

from flask_login import (
    login_user,
    current_user,
    logout_user,
    login_required,
)

from datetime import timedelta, date, datetime
from sqlalchemy.exc import (
    IntegrityError,
    DataError,
    DatabaseError,
    InterfaceError,
    InvalidRequestError,
)

from .main_forms import vehicle_form, status_form, expense_form, hidden_form
import json
import uuid
from sqlalchemy import func


@main.route("/", methods=("GET", "POST"), strict_slashes=False)
def dashboard():
    if current_user.is_authenticated:
        # Data cards
        total_count = db.session.query(Status.status).count()
        total_count2 = db.session.query(func.count(Status.status))

        # Active Card info
        active_count = Status.query.filter_by(status="ACTIVE").count()
        telicon_active_count = len(db.session.query(Status).join(Vehicle).filter(Vehicle.ownership_type == "TELiCON") \
                                   .filter(Status.status == "ACTIVE").all())
        own_third_active = active_count - telicon_active_count

        # Garage Card info
        garage_count = Status.query.filter_by(status="GARAGE").count()
        telicon_garage_count = len(db.session.query(Status).join(Vehicle).filter(Vehicle.ownership_type == "TELiCON") \
                                   .filter(Status.status == "GARAGE").all())
        own_third_garage = garage_count - telicon_garage_count

        # Parked Card info
        parked_count = Status.query.filter_by(status="PARKED").count()
        telicon_parked_count = len(db.session.query(Status).join(Vehicle).filter(Vehicle.ownership_type == "TELiCON") \
                                   .filter(Status.status == "PARKED").all())
        own_third_parked = parked_count - telicon_parked_count

        own_count = db.session.query(Status).join(Vehicle).filter(Vehicle.ownership_type == "Own Vehicle").all()
        third_count = db.session.query(Status).join(Vehicle).filter(Vehicle.ownership_type == "3rd Party").all()

        # Chart
        expense_by_month = db.session.query(db.func.sum(Expense.cost), Expense.month).group_by(Expense.month).order_by(
            Expense.month).all()
        expense_by_year = db.session.query(db.func.sum(Expense.cost), Expense.year).group_by(Expense.year).order_by(
            Expense.year).all()
        expense_over_time = []
        label_over_time = []
        for amount, month in expense_by_month:
            expense_over_time.append(amount)
            label_over_time.append(month)

        return render_template("main/dashboard.html", title="Home", expense_over_time=json.dumps(expense_over_time),
                               label_over_time=json.dumps(label_over_time),
                               active_count=active_count,
                               garage_count=garage_count,
                               parked_count=parked_count,
                               telicon_active_count=telicon_active_count,
                               own_third_active=own_third_active,
                               telicon_garage_count=telicon_garage_count,
                               own_third_garage=own_third_garage,
                               telicon_parked_count=telicon_parked_count,
                               own_third_parked=own_third_parked,
                               )
    else:
        return redirect(url_for('auth.login'))


@main.route("/details", methods=("GET", "POST"), strict_slashes=False)
@login_required
def details():
    vehicles = Vehicle.query
    form = vehicle_form()
    today = date.today()
    # Add new vehicles to the database
    if request.method == 'POST':
        print(request.form)
        try:
            new_vehicle = Vehicle(T_Number=request.form['T_Number'], white_plate=request.form['white_plate'],
                                  green_plate=request.form['green_plate'],
                                  department=request.form['department'],
                                  ownership_type=request.form['ownership_type'],
                                  owner_name=request.form['owner_name'],
                                  driver_name=request.form['driver_name'],
                                  region=request.form['region'],
                                  amber=request.form['amber'],
                                  flow_sticker=request.form['flow_sticker'],
                                  telicon_sticker=request.form['telicon_sticker'],
                                  lpg_gas=request.form['lpg_gas'],
                                  manufacturer=request.form['manufacturer'],
                                  car_model=request.form['car_model'],
                                  year=request.form['year'],
                                  color=request.form['color'],
                                  chasis_number=request.form['chasis_number'],
                                  engine_number=request.form['engine_number'],
                                  service_date=datetime.strptime(request.form['service_date'], "%Y-%m-%d").date(),
                                  registration_exp=datetime.strptime(request.form['registration_exp'],
                                                                     "%Y-%m-%d").date(),
                                  fitness_exp=datetime.strptime(request.form['fitness_exp'], "%Y-%m-%d").date(),
                                  carrier_exp=datetime.strptime(request.form['carrier_exp'], "%Y-%m-%d").date(),
                                  cn_exp=datetime.strptime(request.form['cn_exp'], "%Y-%m-%d").date(),
                                  insurance_exp=datetime.strptime(request.form['insurance_exp'], "%Y-%m-%d").date(),
                                  insurance_company=request.form['insurance_company'],
                                  gas_type=request.form['gas_type']
                                  )
            db.session.add(new_vehicle)
            db.session.commit()
            print('new vehicle added')

            new_status = Status(T_Number=request.form['T_Number'],
                                status="ACTIVE",
                                date_garage=None,
                                garage_reason=None,
                                repair_id=str(uuid.uuid4()),
                                estimated_repair_time=None,
                                date_parked=None,
                                park_reason=None,
                                date_active=today,
                                active_notes=None)
            db.session.add(new_status)
            db.session.commit()
            print('New status added')

        except Exception as e:
            print(e)

        return redirect(url_for('main.details'))

    return render_template("main/details.html", vehicles=vehicles, form=form, today=today)


@main.route('/details/data')
@login_required
def details_data():
    # server side datatable
    query = Vehicle.query

    # search filter
    search = request.args.get('search[value]')

    if search:
        query = query.filter(db.or_(
            Vehicle.T_Number.like(f'%{search}%'),
            Vehicle.driver_name.like(f'%{search}%')
        ))

    total_filtered = query.count()

    # sorting
    order = []
    i = 0
    while True:
        col_index = request.args.get(f'order[{i}][column]')
        if col_index is None:
            break
        col_name = request.args.get(f'columns[{col_index}][data]')
        if col_name not in ['T_Number', 'department', 'region', 'driver_name', 'ownership_type', 'registration_exp',
                            'fitness_exp', 'carrier_exp', 'insurance_exp']:
            col_name = 'T_Number'
        descending = request.args.get(f'order[{i}][dir]') == 'desc'
        col = getattr(Vehicle, col_name)
        if descending:
            col = col.desc()
        order.append(col)
        i += 1
    if order:
        query = query.order_by(*order)

    # pagination
    start = request.args.get('start', type=int)
    length = request.args.get('length', type=int)
    query = query.offset(start).limit(length)

    return {'data': [vehicle.to_dict() for vehicle in query],
            'recordsFiltered': total_filtered,
            'recordsTotal': Vehicle.query.count(),
            'draw': request.args.get('draw', type=int),
            }


@main.route("/update/<T_Number>", methods=("GET", "POST"), strict_slashes=False)
@login_required
def update_details(T_Number):
    # query vehicle details and populate page
    vehicle = Vehicle.query.filter_by(T_Number=T_Number).first()
    form = vehicle_form(obj=vehicle)
    print(form.year)

    if form.validate_on_submit():
        print("success")
        try:
            form.populate_obj(vehicle)
            db.session.commit()
            return redirect(url_for('main.details'))

        except Exception as e:
            flash(e, "danger")

    return render_template("main/update.html",
                           T_Number=T_Number,
                           form=form
                           )


@main.route("/active", methods=("GET", "POST"), strict_slashes=False)
@login_required
def active():
    # Query the list of vehicles in the garage
    active_vehicles = Status.query.filter_by(status="ACTIVE")

    # Initialize the forms needed for updating status and expense
    active_status = status_form()
    hidden = hidden_form()

    # if update form is submitted
    if request.method == 'POST':
        print("success")
        status = Status.query.filter_by(T_Number=request.form['T_Number']).first()
        active_status = status_form(obj=request.form)
        print(request.form)
        try:

fleetdashboard/main/templates/main/active.html
{% extends 'main/base.html' %}

{% block content %}

    <!-- Modal for selecting option-->
    <div class="modal fade" id="optionModal" tabindex="-1" aria-labelledby="optionModalLabel" aria-hidden="true">]
        <div class="modal-dialog modal-dialog-centered" id="option-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h8 class="modal-title" id="optionModalLabel">Select an option</h8>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body-option">
                    <button class="btn btn-primary" id="test" data-bs-target="#updateModal" data-bs-toggle="modal" data-bs-dismiss="modal">Update Status</button>
                    <button class="btn btn-primary" data-bs-target="#changeModal" data-bs-toggle="modal" data-bs-dismiss="modal">Change Status</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for update status-->
    <div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">]
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateModallLabel">Update Status</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body-update">
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for change status-->
    <div class="modal fade" id="changeModal" tabindex="-1" aria-labelledby="changeModalLabel" aria-hidden="true">]
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h8 class="modal-title" id="changeModalLabel">Select an option</h8>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body-option">
                    <button class="btn btn-primary change-options" id="park" data-bs-target="#updateModal" data-bs-toggle="modal" data-bs-dismiss="modal" >Park</button>
                    <button class="btn btn-primary change-options" id="garage" data-bs-target="#updateModal" data-bs-toggle="modal" data-bs-dismiss="modal">Garage</button>
                </div>
            </div>
        </div>
    </div>
<!-- Table for displaying status information -->
    <table id="active-table" class="table table-striped table-bordered" style="width:99%">
        <thead>
            <tr>
                <th>T-Number</th>
                <th>Date Active</th>
                <th>Active Notes</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>

{% block scripts %}
  <script>

  </script>
{% endblock %}

{% endblock %}

fleetdashboard/main/templates/main/active_update.html
<div class="modal-body-update">
    <form method ="POST" class="update-form" id="active-form" action="{{ url_for('main.active') }}">
        {{ form.csrf_token }}
        <table class="table">
            <!--hidden page name-->
            <input type="hidden" id="page_name_hidden" value="">
            <tr>
                <td class="form-label">{{ form.T_Number.label}}</td>
                <td>{{ form.T_Number}}</td>
            </tr>
            <tr>
                <td class="form-label">{{ form.status.label}}</td>
                <td>{{ form.status }}</td>
            </tr>
            <tr>
                <td class="form-label">{{ form.date_active.label}}</td>
                <td>{{ form.date_active}}</td>
            </tr>
            <tr>
                <td class="form-label">{{ form.active_notes.label}}</td>
                <td>{{ form.active_notes}}</td>
            </tr>
            <tr>
                <td class="form-label">{{ form.estimated_repair_time.label}}</td>
                <td>{{ form.estimated_repair_time}}</td>
            </tr>
            <tr>
                <td class="form-label">Estimated Cost</td>
                <td>{{ expense }}<span><a class="edit_cost" data-bs-toggle="modal" data-bs-target="#editcostModal" data-bs-dismiss="modal" data-id="{{form.repair_id.data}}" ><span><i class="fas fa-plus-circle"></i></span></a></span></td>
            </tr>

        </table>
        <div class="form-group  sub-btn">
            <button type="submit" class="btn btn-primary" id="status-submit">Submit</button>
        </div>
    </form>
</div>

fleetdashboard/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="UTF-8">
		<title>TELiCON Fleet Dashboard</title>
		<!-- CSRF TOKEN -->
		<meta name="csrf-token" content="{{ csrf_token() }}">
		<!-- AJAX -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
		<!-- Google fonts roboto -->
		<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css">
		<!-- Custom CSS -->
		<link href="{{ url_for('static', filename='/css/custom.css') }}" rel="stylesheet">
		<!--Font Awesome icons -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
		<!--Chart js -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js" integrity="sha512-TW5s0IT/IppJtu76UbysrBH9Hy/5X41OTAbQuffZFU6lQ1rdcLHzpU5BzVvr/YFykoiMYZVWlr/PX1mDcfM9Qg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

	</head>
	<body id="site">
		<div class="page">
			<div class="sidebar">
				<div id="sidebar-header">
					<h2>Fleet</h2>
					<span class="side_btn"><button id="sidebarToggle" class="btn sidebarToggle" onclick="toggleCollapse();"><i class="fas fa-bars"></i></button></span>
				</div>

				<div class="sidebar-body">
					<ul class="nav-list">
						<li class="nav-list-item"><a href="{{ url_for('main.dashboard')}}">
							<div class="icon-container"><i class="fas fa-home"></i></div>
							<span class="nav-label">Dashboard</span></a>
						</li>
						<li class="nav-list-item"><a href="{{ url_for('main.garage')}}">
							<div class="icon-container"><i class="fas fa-wrench"></i></div>
							<span class="nav-label">Garage</span></a>
						</li>
						<li class="nav-list-item"><a href="{{ url_for('main.parked')}}">
							<div class="icon-container"><i class="fas fa-parking"></i></div>
							<span class="nav-label">Parked</span></a>
						</li>
						<li class="nav-list-item"><a href="{{ url_for('main.active')}}">
							<div class="icon-container"><i class="fas fa-car"></i></div>
							<span class="nav-label">Active</span></a>
						</li>
						<li class="nav-list-item"><a href="{{ url_for('main.details')}}">
							<div class="icon-container"><i class="fas fa-sliders-h"></i></div>
							<span class="nav-label">Vehicle Management</span></a>
						</li>
						<li class="nav-list-item"><a href="{{ url_for('main.expenses')}}">
							<div class="icon-container"><i class="fas fa-money-bill-wave-alt"></i></div>
							<span class="nav-label">Expenses</span></a>
						</li>
					</ul>
				</div>
			</div>
			<div class="content">
				<div class="navigationBar">
					<ul class="navbar-items-list">
						<li class="navbar-item">
							<!--Notification dropdown-->
							<div class="notif-container">
								<a href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
									<div class="icon-container"><i class="fas fa-bell"></i></div>
								</a>
								<span class="badge rounded-circle bg-danger"></span>
								<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li id="loader-container"><div class="loader"></div></li>
                                </ul>
							</div>
						</li>
						<li class="navbar-item"><a href="{{ url_for('auth.logout')}}">
							<span class="nav-label">Logout</span></a>
						</li>
					</ul>
				</div>
				<div class="content-container">
				{% block content %} {% endblock %}
				</div>
			</div>
		</div>
		<!--Bootsrap js-->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
		<!--Datatables js-->
		<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
		<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.js"></script>
		<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/2.1.0/js/dataTables.buttons.min.js"></script>
		<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/yadcf/0.9.4/jquery.dataTables.yadcf.min.js"></script>
		<!--Moment Date manager-->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
		<script src="http://cdn.datatables.net/plug-ins/1.10.15/dataRender/datetime.js"></script>
		<script src="https://cdn.datatables.net/plug-ins/1.10.21/sorting/datetime-moment.js"></script>
		<!--Custom JS-->
		<script src="{{ url_for('static', filename='/js/sidebar_collapse.js') }}"></script>
		<script src="{{ url_for('static', filename='/js/status.js') }}"></script>
		<script src="{{ url_for('static', filename='/js/expense.js') }}"></script>
		<script src="{{ url_for('static', filename='/js/add_form_row.js') }}"></script>
		<script src="{{ url_for('static', filename='/js/precheck_boxes.js') }}"></script>
		<script src="{{ url_for('static', filename='/js/cost_actions.js') }}"></script>
		<script src="{{ url_for('static', filename='/js/update_detail.js') }}"></script>
		<script src="{{ url_for('static', filename='/js/datatables.js') }}"></script>
		<script src="{{ url_for('static', filename='/js/notification.js') }}"></script>
	</body>
</html>

fleetdashboard/main/templates/main/dashboard.html
{% extends 'main/base.html' %}

{% block content %}

    <section class="py-5 dash-summary">
		<div class="dash-facts-containter">
			<div class="row" id="status-row">
				<div class="col-sm dash-text" >
					<div class="ms-5 me-1 dash-icon"><i class="fas fa-car"></i></div>
					<div class="mx-2"><h3>Active</h3>
					<p class="subtext">No of. Telicon:{{ telicon_active_count }} </p>
					<p class="subtext">No of Own/3rd Party:{{ own_third_active }}</p>
					<p>Total No. of Active: {{ active_count }}</p></div>
              	</div>
				<div class="col-sm dash-text">
					<div class="ms-5 me-1 dash-icon"><i class="fas fa-wrench"></i></div>
					<div><h3>Garage</h3>
					<p class="subtext">No of. Telicon: {{ telicon_garage_count }}</p>
					<p class="subtext">No of Own/3rd Party: {{ own_third_garage }}</p>
					<p>Total No. of Garage: {{ garage_count }}</p></div>
              	</div>
				<div class="col-sm dash-text">
					<div class="ms-5 me-1 dash-icon"><i class="fas fa-parking"></i></div>
					<div><h3>Parked</h3>
					<p class="subtext">No of. Telicon: {{ telicon_parked_count }}</p>
					<p class="subtext">No of Own/3rd Party: {{ own_third_parked }}</p>
					<p>Total No. of Parked: {{ parked_count }}</p></div>
              	</div>
            </div>
		</div>
	</section>

	<!--Card for expenses chart-->
    <div class="chart-card-container">
        <div class="card card-style mb-4">
            <div class="card-body">
                <div class="chart-container" style="position: relative;">
                    <canvas id="expense_chart"></canvas>
                </div>
            </div>
        </div>
    </div>

{% block scripts %}
<script>
        let expense = JSON.parse({{ expense_over_time | tojson }})
        let labels = JSON.parse({{ label_over_time | tojson }})

        const data = {
            labels: labels,
            datasets: [{
              label: 'Cost',
              backgroundColor: '#CC0000',
              borderColor: 'rgb(255, 99, 132)',
              data: expense
            }]
        };

        const config = {
            type: 'bar',
            data: data,
            options: {
                maxBarThickness: 30,
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    title: {
                              display: true,
                              text: 'Monthly Expenses'
                    }
                }
            }
        };

        const myChart = new Chart(
            document.getElementById('expense_chart'),
            config
        );
    </script>
{% endblock %}
{% endblock %}

fleetdashboard/main/templates/main/details.html
{% extends 'main/base.html' %}

{% block content %}

   <!-- Modal for new vehicle-->
    <div class="modal fade" id="newvehicleModal" tabindex="-1" aria-labelledby="newvehicleModalLabel" aria-hidden="true">]
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="newvehicleModalLabel">Add new vehicle</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body-new-vehicle">
                    <div class="details_container">
                        <form method ="POST" class="edit-form" id="edit-form">
                            {{ form.csrf_token }}
                            <table class=" table update_table">
                            {% for field_row in form | batch(3, '&nbsp;') %}
                                {% if loop.index < 7 %}
                                    <tr class="detail-row">
                                        {% for field in field_row %}
                                            <td class="detail-td">
                                                {{ field.label }}
                                                {{ field }}
                                                {% for error in field.errors %}
                                                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                        {{ error }}
                                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    </div>
                                                {% endfor %}
                                            </td>
                                        {% endfor %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            </table>

                            {% for field in form if field.widget.input_type != 'hidden' %}
                                {% if loop.index == 19  %}
                                    {{ field.label }}
                                    {{ field }}
                                        {% for error in field.errors %}
                                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                {{ error }}
                                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                            </div>
                                        {% endfor %}
                                {% endif %}
                             <!--date widgets-->
                                {% if loop.index >= 20 and loop.index < 26 %}
                                    {{ field.label }}
                                    {{ field(class="date-form-fields", placeholder="") }}
                                    {% for error in field.errors %}
                                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                            {{ error }}
                                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}

                            {{ form.insurance_company.label }}
                            {{ form.insurance_company }}
                            {% for error in form.insurance_company.errors %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                    {{ error }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            {% endfor %}

                            {{ form.gas_type.label }}
                            {{ form.gas_type }}
                            {% for error in form.gas_type.errors %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                    {{ error }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            {% endfor %}

                          <div class="form-group">
                              <button type="submit" class="btn btn-primary" id="detail-submit" >Submit</button>
                          </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

  <table id="data" class="table table-striped table-bordered" style="width:100%">
    <thead>
      <tr>
          <th>T-Number</th>
          <th>Department</th>
          <th>Driver</th>
          <th>Ownership</th>
          <th>Last Service Date</th>
          <th>Registration</th>
          <th>Fitness</th>
          <th>Carrier</th>
          <th>Insurance</th>
          <th>Edit</th>
      </tr>
    </thead>
    <tbody>

    </tbody>
  </table>

{% block scripts %}

{% endblock %}

{% endblock %}

fleetdashboard/main/templates/main/expense_response.html
<thead class="table-primary">
    <tr>
        <th id="cost-modal-header">
            <button type="button" class="btn btn-info add-cost-btn" data-id="{{repair_id}}" data-tn="{{t_num}}" ><i class="fa fa-plus"></i>Add New</button>
            <span class='btn btn-danger' id="displaymessage"></span>
        </th>

    </tr>
</thead>
<tbody>
    <tr>
        <td>
            <div class = "costs">
                <table class=" table expense-table">
                    <tbody class="cost-body">
                        {% for row in cost_list%}
                        <tr>
                            <td style="display:none;">{{ row.id }}</td>
                            <td style="display:none;">{{ row.repair_id }}</td>
                            <td style="display:none;">{{ t_num }}</td>
                            <td>{{ row.cost_description }}</td>
                            <td>{{ row.cost }}</td>
                            <td><input class="paid_box" type="checkbox" value="{{ row.expense_status}}" name="paid_box" disabled="disabled"></td>
                            <td>
                                <a class="add-cost"><i class="fas fa-plus-square"></i></a>
                                <a class="edit-cost"><i class="fas fa-pencil-alt"></i></a>
                                <a class="delete-cost"><i class="fas fa-trash-alt" data-id="{{repair_id}}"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                 <button class="btn btn-primary" data-bs-target="#updateModal" data-bs-toggle="modal" data-bs-dismiss="modal">Back</button>
            </div>
        </td>
    </tr>
</tbody>

fleetdashboard/main/templates/main/history.html
<table class="table">
    <thead class="table-primary">
        <tr>
            <th>T-Number</th>
            <th>Date</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        {% for record in history %}
        <tr>
            <td>{{ record.T_Number  }}</td>
            <td>{{ record.date_garage }}</td>
            <td>{{ record.garage_reason }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>